// Generated by gencpp from file test_pkg/CarInfo.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_CARINFO_H
#define TEST_PKG_MESSAGE_CARINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace test_pkg
{
template <class ContainerAllocator>
struct CarInfo_
{
  typedef CarInfo_<ContainerAllocator> Type;

  CarInfo_()
    : header()
    , vehicle_id(0)
    , location()  {
    }
  CarInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicle_id(0)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _vehicle_id_type;
  _vehicle_id_type vehicle_id;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::test_pkg::CarInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::CarInfo_<ContainerAllocator> const> ConstPtr;

}; // struct CarInfo_

typedef ::test_pkg::CarInfo_<std::allocator<void> > CarInfo;

typedef boost::shared_ptr< ::test_pkg::CarInfo > CarInfoPtr;
typedef boost::shared_ptr< ::test_pkg::CarInfo const> CarInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::CarInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::CarInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_pkg::CarInfo_<ContainerAllocator1> & lhs, const ::test_pkg::CarInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vehicle_id == rhs.vehicle_id &&
    lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_pkg::CarInfo_<ContainerAllocator1> & lhs, const ::test_pkg::CarInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test_pkg::CarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::CarInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::CarInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::CarInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::CarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::CarInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98bbad100463b9a4aa2857a0a9b4dacc";
  }

  static const char* value(const ::test_pkg::CarInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98bbad100463b9a4ULL;
  static const uint64_t static_value2 = 0xaa2857a0a9b4daccULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/CarInfo";
  }

  static const char* value(const ::test_pkg::CarInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 该消息用于传递车辆ID和位置信息\n"
"# 位置信息包括x、y、z三个坐标值\n"
"Header header\n"
"int32 vehicle_id\n"
"float32[] location\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::test_pkg::CarInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::CarInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicle_id);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::CarInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::CarInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicle_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vehicle_id);
    s << indent << "location[]" << std::endl;
    for (size_t i = 0; i < v.location.size(); ++i)
    {
      s << indent << "  location[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.location[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_CARINFO_H
